name: Acceptance Tests

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/acceptance.yml"
      - "backend/**"
      - "frontend/**"
    branches:
       - main
jobs:

  build:
    runs-on: [self-hosted,fred]
    strategy:
      matrix:
        include:
          - image: backend
            file: Dockerfile.acceptance
          - image: frontend
            file: Dockerfile
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            plone/ploneconf-${{ matrix.image }}
          tags: |
            type=sha
            type=raw,value=acceptance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ matrix.image }}-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}
          path: ${{ runner.temp }}/${{ matrix.image }}-image.tar

  acceptance-test:
    runs-on: [self-hosted,fred]
    needs:
      - build
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Backend
        uses: actions/download-artifact@v3
        id: download-backend
        with:
          name: backend
          path: ${{ runner.temp }}

      - name: Download frontend
        uses: actions/download-artifact@v3
        id: download-frontend
        with:
          name: frontend
          path: ${{ runner.temp }}

      - name: 'Echo download paths'
        run: |
          ls ${{steps.download-backend.outputs.download-path}}
          ls ${{steps.download-frontend.outputs.download-path}}

      - name: Load Docker Images
        run: |
          docker load --input ${{ runner.temp }}/backend-image.tar
          docker load --input ${{ runner.temp }}/frontend-image.tar

      - name: Install Cypress
        run: npm i @plone/volto-testing

      - name: Cypress acceptance tests
        uses: cypress-io/github-action@v5
        env:
          BABEL_ENV: production
          CYPRESS_RETRIES: 2
        with:
          parallel: false
          browser: chrome
          spec: cypress/integration/**/*.cy.js
          working-directory: frontend
          install: false
          start: |
            docker compose -f cypress/compose.yml up
          wait-on: 'npx wait-on --httpTimeout 20000 http-get://localhost:55001/plone http://localhost:3000'
