name: Manual Deploy

on:
  workflow_dispatch:

env:
  LIVE_ENV: "2023.ploneconf.org"
  STG_ENV: "testing.ploneconf.org"

jobs:

  meta:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.vars.outputs.ENVIRONMENT }}
      STACK_NAME: ${{ steps.vars.outputs.STACK_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Env Vars
        id: vars
        run: |
          echo "ENVIRONMENT=$(if [ ${GITHUB_REF##*/} == 'main' ]; then echo ${{ env.LIVE_ENV }}; else echo ${{ env.STG_ENV }}; fi)" >> $GITHUB_OUTPUT
          echo "STACK_NAME=${ENVIRONMENT/./_}" >> $GITHUB_OUTPUT

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs:
      - meta
    environment: ${{ needs.meta.outputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: devops/stacks/${{ needs.meta.outputs.ENVIRONMENT }}.yml
          stack_name: ${{ needs.meta.outputs.STACK_NAME }}
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480
