name: Manual Deploy

on:
  workflow_dispatch:

jobs:

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: testing.ploneconf.org
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to 2023.ploneconf.org
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: "devops/stacks/testing.ploneconf.org.yml"
          stack_name: "ploneconftesting"
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480
